# Generated by Django 3.2.6 on 2025-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_venda', models.DateField()),
                ('quantidade_entregas', models.IntegerField()),
                ('venda_dinheiro', models.DecimalField(decimal_places=2, max_digits=7)),
                ('venda_cartao', models.DecimalField(decimal_places=2, max_digits=7)),
                ('compras', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descricao_compras', models.CharField(blank=True, max_length=200, null=True)),
                ('despesas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descricao_despesas', models.CharField(blank=True, max_length=200, null=True)),
                ('venda_total_dia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('despesa_do_dia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('lucro_liquido_dia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'unique_together': {('dia_da_venda',)},
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descricao_salario', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'unique_together': {('nome', 'telefone')},
            },
        ),
    ]
