# Generated by Django 3.2.6 on 2021-08-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField(auto_now_add=True)),
                ('quantidade_entrega', models.IntegerField()),
                ('venda_dinheiro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('venda_cartao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('compras', models.DecimalField(decimal_places=2, max_digits=5)),
                ('despesas', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
