# Generated by Django 3.2.6 on 2021-08-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vendadiaria_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendadiaria',
            old_name='quantidade_entrega',
            new_name='quantidade_entregas',
        ),
    ]
