# Generated by Django 3.2.6 on 2021-08-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comprasmensal_despesamensal_lucroliquido_vendamensalcartao_vendamensaldinheiro_vendamensaltotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendadiaria',
            name='descricao_compras',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendadiaria',
            name='descricao_despesas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
