# Generated by Django 3.2.6 on 2021-08-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210823_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendadiaria',
            name='venda_total_dia',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
