# Generated by Django 3.2.6 on 2021-08-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendadiaria_venda_total_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendadiaria',
            name='dia',
            field=models.DateField(),
        ),
    ]
