# Generated by Django 3.2.6 on 2021-08-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210823_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendadiaria',
            name='despesa_do_dia',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
