# Generated by Django 3.2.6 on 2021-08-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210823_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendamensaldinheiro',
            name='venda_mensal',
            field=models.ManyToManyField(blank=True, to='core.VendaDiaria'),
        ),
    ]
