# Generated by Django 3.2.6 on 2021-08-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vendamensaldinheiro_venda_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendamensaldinheiro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
