# Generated by Django 3.2.6 on 2021-08-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vendamensaldinheiro_valor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendaDiaria',
            new_name='Venda',
        ),
        migrations.DeleteModel(
            name='ComprasMensal',
        ),
        migrations.DeleteModel(
            name='DespesaMensal',
        ),
        migrations.DeleteModel(
            name='EntregaMes',
        ),
        migrations.DeleteModel(
            name='LucroLiquido',
        ),
        migrations.DeleteModel(
            name='VendaMensalCartao',
        ),
        migrations.RemoveField(
            model_name='vendamensaldinheiro',
            name='venda_mensal',
        ),
        migrations.DeleteModel(
            name='VendaMensalTotal',
        ),
        migrations.DeleteModel(
            name='VendaMensalDinheiro',
        ),
    ]
