# Generated by Django 3.2.6 on 2021-08-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210823_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='venda_dinheiro_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
