# Generated by Django 3.2.6 on 2021-08-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_venda_venda_dinheiro_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='lucro_liquido',
            new_name='lucro_liquido_dia',
        ),
        migrations.AddField(
            model_name='venda',
            name='venda_cartao_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
