# Generated by Django 3.2.6 on 2021-08-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210827_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='dia',
            new_name='dia_da_venda',
        ),
    ]
