# Generated by Django 3.2.6 on 2021-09-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_dia_venda_dia_da_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='venda_cartao_total',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='venda_dinheiro_total',
        ),
        migrations.AlterField(
            model_name='venda',
            name='quantidade_entregas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='venda_cartao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='venda',
            name='venda_dinheiro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
