# Generated by Django 3.2.6 on 2021-09-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210901_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='compras',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='venda',
            name='despesas',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='venda',
            name='quantidade_entregas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='venda_cartao',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='venda',
            name='venda_dinheiro',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
