# Generated by Django 3.2.6 on 2021-09-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210901_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='dia_da_venda',
            field=models.DateField(verbose_name='oi'),
        ),
    ]
