# Generated by Django 3.2.6 on 2021-09-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_venda_dia_da_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='dia_da_venda',
            field=models.DateField(verbose_name='Dia da venda ex: 01/12/2020'),
        ),
    ]
