# Generated by Django 3.2.6 on 2021-09-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210901_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='dia_da_venda',
            field=models.DateField(),
        ),
    ]
