# Generated by Django 3.2.6 on 2021-09-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_colaborador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
