# Generated by Django 3.2.6 on 2021-09-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_colaborador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
