# Generated by Django 3.2.6 on 2021-09-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_endereço_colaborador_endereco'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colaborador',
            unique_together={('nome', 'telefone')},
        ),
        migrations.AlterUniqueTogether(
            name='venda',
            unique_together={('dia_da_venda', 'quantidade_entregas', 'venda_dinheiro', 'venda_cartao')},
        ),
    ]
