# Generated by Django 3.2.6 on 2021-09-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210929_1124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venda',
            unique_together={('dia_da_venda',)},
        ),
    ]
