# Generated by Django 3.2.6 on 2021-09-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_cadastroacrescimos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField(auto_now=True)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão')], max_length=20)),
                ('valor_pagar', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('acai_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.cadastroacai')),
                ('acrescimo_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.cadastroacrescimos')),
            ],
        ),
    ]
