# Generated by Django 3.2.6 on 2021-09-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_observacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='acai_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='acai_pedido',
            field=models.ManyToManyField(to='pedidos.CadastroAcai'),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='acrescimo_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='acrescimo_pedido',
            field=models.ManyToManyField(to='pedidos.CadastroAcrescimos'),
        ),
    ]
