# Generated by Django 3.2.6 on 2021-09-12 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20210910_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('acai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.cadastroacai')),
                ('acrescimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.cadastroacrescimos')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
    ]
