# Generated by Django 3.2.6 on 2021-09-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_itemdopedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemDoPedido',
            new_name='ItemDoPedidoAcai',
        ),
    ]
