# Generated by Django 3.2.6 on 2021-09-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_rename_itemdopedido_itemdopedidoacai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdopedidoacai',
            name='acrescimo',
        ),
    ]
