# Generated by Django 3.2.6 on 2021-09-12 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_remove_itemdopedidoacai_acrescimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDoPedidoAcre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('acrescimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.cadastroacrescimos')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
    ]
