# Generated by Django 3.2.6 on 2021-09-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_itemdopedidoacre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='acai_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='acrescimo_pedido',
        ),
    ]
