# Generated by Django 3.2.6 on 2021-10-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_auto_20210912_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastroAcai',
            new_name='Acai',
        ),
        migrations.RenameModel(
            old_name='CadastroAcrescimos',
            new_name='Acrescimo',
        ),
    ]
